### ISSUE TITLE
Doesn't compile on Arch Linux 4.18.4. IPCPointerMove not declared here.

### ISSUE THREAD

**Issue by FlashDaggerX** [JLErvin/berry#1]
**OS** Arch Linux 4.18.4-arch1-1-ARCH

Tried to compile into a pacman package, but `cc` stopped when the compiler threw this (Stripped for formatting):
`cc -Os -pedantic -Wall -D__NAME__=\"berry\" -D__NAME_CLIENT__=\"berryc\" -D__THIS_VERSION__=\"0.0.1\" -D__CONFIG_NAME__=\"autostart\"  -I/usr/include wm.c -L/usr/lib -lX11 -lm -o berry`

`wm.c:190:6: error: ‘IPCPointerMove’ undeclared here (not in a function); did you mean ‘PointerRoot’?`
`wm.c:190:6: error: array index in initializer not of integer type
wm.c:190:6: note: (near initialization for ‘ipc_handler’)
make: *** [Makefile:12: all] Error 1
`

`libx11` is installed.

**Comment by FlashDaggerX** [comment]
I noticed in your Makefile that you're trying to use a different prefix for X11, one that doesn't exist on our systems.
`/usr/X11R6/`

**Comment by JLErvin** [comment]
Looks like you're on version 0.0.1. Try upgrading to version 0.0.2 and see if the error persisits. Looks like you're using an old version of `ipc.h` which doesn't contain the IPCPointerMove command.

**Comment by FlashDaggerX** [comment]
Yea, that was it, thanks. I usually use release tags for making packages.

Closed.
